server:
  port: 0

spring:
  application:
    name: order
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5436/orderdb"
    username: "order_user"
    password: "12345"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always

order:
  default:
    warehouse:
      from: "1"
      to: "2"
