services:
  db-warehouse:
    image: postgres:16.1
    container_name: warehouse-postgres
    ports:
      - "5434:5434"
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=warehousedb
      - POSTGRES_USER=warehouse_user
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  db-init-warehouse:
    image: postgres:16.1
    container_name: db-init-warehouse
    depends_on:
      db-warehouse:
        condition: service_healthy
    entrypoint:
      - bash
      - -c
      - |
        set -e
        psql postgresql://warehouse_user:12345@db-warehouse:5434/warehousedb -v ON_ERROR_STOP=1 <<-EOSQL
          CREATE TABLE IF NOT EXISTS items (
                      id varchar(100) PRIMARY KEY,
                      quantity_in_warehouse bigint,
                      fragile boolean,
                      weight real,
                      width real,
                      height real,
                      depth real
          );
        
          CREATE TABLE IF NOT EXISTS warehouses (
                      id varchar(100) PRIMARY KEY,
                      address_city VARCHAR(64),
                      address_street VARCHAR(128),
                      address_house VARCHAR(4),
                      address_country VARCHAR(32),
                      address_flat VARCHAR(4)
          );
        EOSQL