server:
  port: 0

application:
  name: aggregator

aggregator:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      client-id: sensor-event-consumer
      group-id: aggregator-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.yandex.practicum.serializer.SensorEventDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.yandex.practicum.serializer.AggregatorSerializer