services:
  db:
    image: postgres:16.1
    container_name: cart-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=cartdb
      - POSTGRES_USER=cart_user
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  db-init:
    image: postgres:16.1
    container_name: db-init
    depends_on:
      db:
        condition: service_healthy
    entrypoint:
      - bash
      - -c
      - |
        set -e
        psql postgresql://cart_user:12345@db:5432/cartdb -v ON_ERROR_STOP=1 <<-EOSQL
          CREATE TABLE IF NOT EXISTS Carts (
                      id varchar(100) PRIMARY KEY,
                      username varchar(50) NOT NULL,
                      active boolean NOT NULL DEFAULT true
          );
  
          CREATE TABLE IF NOT EXISTS Products (
                      cart_id varchar(100) REFERENCES Carts(id) ON DELETE CASCADE,
                      product_id varchar(100) NOT NULL,
                      quantity bigint NOT NULL,
                      PRIMARY KEY(cart_id, product_id)
          );
        EOSQL