application:
  name: analyzer

grpc:
  client:
    hub-router:
      address: static://localhost:59090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/analyzer
    username: dbuser
    password: 12345
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always

analyzer:
  kafka:
    bootstrap-servers: localhost:9092
    snapshot-consumer:
      client-id: snapshot-analyzer-group
      group-id: snapshot-event-consumer
      value-deserializer: ru.yandex.practicum.deserializer.SnapshotDeserializer
    hub-consumer:
      client-id: hub-analyzer-group
      group-id: hub-event-consumer
      value-deserializer: ru.yandex.practicum.deserializer.HubEventDeserializer
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer