server:
  port: 0

spring:
  application:
    name: shopping-store
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/storedb"
    username: "store_user"
    password: "12345"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: store
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
